### ISSUE TITLE
Are you sure handling for battery is okay?

### ISSUE THREAD

**Issue by avbentem** [SensationalSystems/IMBuildings_People_Counter#1]
Looking at the code of [decoder.js](https://github.com/SensationalSystems/IMBuildings_People_Counter/blob/master/decoder.js), I see:

```javascript
params.battery = (bytes[11] << 8) | bytes[12] / 100;
```

This is the same as:

```javascript
params.battery = (bytes[11] << 8) | (bytes[12] / 100);
```

As a bitwise OR expects integers, not decimals, I doubt that's what's expected. Instead, I'd assume one wants:

```javascript
params.battery = (bytes[11] << 8 | bytes[12]) / 100;
```

The above still allows for very large battery values, ranging from 0 thru 655.35, which smells. One may want to validate in the device's documentation.

**:warning: I do not own this device.**

Aside, note that parentheses are not needed below, as in JavaScript [shifting has a higher precedence than the bitwise OR operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence):

```javascript
(bytes[11] << 8) | (bytes[12]
```

(Parentheses would be needed when using addition rather than the bitwise OR.)

**Comment by cazagen** [comment]
The first part is very true, I totally missed that!

As for the unneeded parentheses that is totally true, but I like keeping them in as it is clear to people the order of precedence
